services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDISHOST=redis
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: